src/Dpp/CustomersBundle/Entity/Customer.php
<?php

namespace Dpp\CustomersBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Dpp\CustomersBundle\Entity\Product;
use Dpp\CustomersBundle\Controller\AllTypeController;
use Dpp\AjaxServeurBundle\Entity\PromoCodeInterface;
use Symfony\Component\Validator\ExecutionContextInterface;

/**
 * Customer
 *
 * @ORM\Table()
 * @ORM\Table(name="dpp_customer")
 * @ORM\Entity(repositoryClass="Dpp\CustomersBundle\Entity\CustomerRepository")
 * @UniqueEntity("domaine")
 */
 
class Customer implements PromoCodeInterface
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="domaine", type="string", length=255, unique=true)
     */
    private $domaine;

    /**
     * @var integer
     *
     * @ORM\Column(name="pricingType", type="integer", nullable=true)
     */
    private $pricingType;

    /**
     * @var integer
     *
     * @ORM\Column(name="visitTimeInterval", type="integer")
     */
    private $visitTimeInterval;
    
     /**
     * @var integer
     *
     * @ORM\Column(name="importType", type="integer")
     */
    private $importType;
    
     /**
     * @var longtext
     *
     * @ORM\Column(name="promoCodes", type="text", nullable=true)
     */
    private $promoCodes;

    /**
    * @ORM\OneToMany(targetEntity="Dpp\CustomersBundle\Entity\Product", mappedBy="customer")
    */
    private $products; 
    
    /**
     * @var string
     *
     * @ORM\Column(name="defaultMsg", type="string", length=255)
     */
    private $defaultMsg;
    
    /**
     * @var boolean
     *
     * @ORM\Column(name="autoAcquisition", type="boolean")
     */
    private $autoAcquisition;

    /**
     * @var boolean
     *
     * @ORM\Column(name="globalPromo", type="boolean")
     */
    private $globalPromo;
    
    /**
     * @var boolean
     *
     * @ORM\Column(name="categoryPromo", type="boolean")
     */
    private $categoryPromo;
    
    
    
    
    
    /**
    * Constructor
    */
    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Customer
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set domaine
     *
     * @param string $domaine
     * @return Customer
     */
    public function setDomaine($domaine)
    {
        $this->domaine = $domaine;

        return $this;
    }

    /**
     * Get domaine
     *
     * @return string 
     */
    public function getDomaine()
    {
        return $this->domaine;
    }

    /**
     * Set pricingType
     *
     * @param integer $pricingType
     * @return Customer
     */
    public function setPricingType($pricingType)
    {
        $this->pricingType = $pricingType;
        return $this;
    }

    /**
     * Get pricingType
     *
     * @return integer 
     */
    public function getPricingType()
    {
        return $this->pricingType;
    }

    /**
     * Set visitTimeInterval
     *
     * @param integer $visitTimeInterval
     * @return Customer
     */
    public function setVisitTimeInterval($visitTimeInterval)
    {
        $this->visitTimeInterval = $visitTimeInterval;
        return $this;
    }

    /**
     * Get visitTimeInterval
     *
     * @return integer 
     */
    public function getVisitTimeInterval()
    {
        return $this->visitTimeInterval;
    }
    
    /**
     * Set importType
     *
     * @param integer $importType
     * @return Customer
     */
    public function setImportType($importType)
    {
        $this->importType = $importType;
        return $this;
    }

    /**
     * Get importType
     *
     * @return integer 
     */
    public function getImportType()
    {
        return $this->importType;
    }
    
    /**
     * Set promoCodes
     *
     * @param longtext $promoCodes
     * @return Customer
     */
    public function setPromoCodes($promoCodes)
    {
        $this->promoCodes = $promoCodes;
        return $this;
    }

    /**
     * Get promoCodes
     *
     * @return longtext 
     */
    public function getPromoCodes()
    {
        return $this->promoCodes;
    }
    
    /*
    * get promoCode as array
    * retur array or false
    */
    public function getPromoCodesAsArray()
    {
        if ($this->getPromoCodes() == null) return FALSE;
        return json_decode($this->getPromoCodes());
    }
    
    /**
     * Set defaultMsg
     *
     * @param string $defaultMsg
     * @return Customer
     */
    public function setDefaultMsg($defaultMsg)
    {
        $this->defaultMsg = $defaultMsg;

        return $this;
    }

    /**
     * Get defaultMsg
     *
     * @return string 
     */
    public function getDefaultMsg()
    {
        return $this->defaultMsg;
    }
    
    /**
     * Set autoAcquisition
     *
     * @param boolean $autoAcquisition
     * @return Customer
     */
    public function setAutoAcquisition($autoAcquisition)
    {
        $this->autoAcquisition = $autoAcquisition;

        return $this;
    }

    /**
     * Get autoAcquisition
     *
     * @return boolean 
     */
    public function getAutoAcquisition()
    {
        return $this->autoAcquisition;
    }
    public function isAutoAcquisition()
    {
        return $this->autoAcquisition;
    }
    
    /**
     * Set globalPromo
     *
     * @param boolean $globalPromo
     * @return Customer
     */
    public function setGlobalPromo($globalPromo)
    {
        $this->globalPromo = $globalPromo;

        return $this;
    }

    /**
     * Get globalPromo
     *
     * @return boolean 
     */
    public function getGlobalPromo()
    {
        return $this->globalPromo;
    }
    public function isGlobalPromo()
    {
        return $this->globalPromo;
    }
    /**
     * Set categoryPromo
     *
     * @param boolean $categoryPromo
     * @return Customer
     */
    public function setCategoryPromo($categoryPromo)
    {
        $this->categoryPromo = $categoryPromo;

        return $this;
    }

    /**
     * Get globalPromo
     *
     * @return boolean 
     */
    public function getCategoryPromo()
    {
        return $this->categoryPromo;
    }
    public function hasCategoryPromo()
    {
        return $this->categoryPromo;
    }
    public function hasCategory()
    {
        return $this->categoryPromo;
    }
    
    /**
    * Add, remove, and get Product collection
    */
    
    public function addProduct(Product $product)
    {
        $this->products[] = $product;
        $product->setCustomer($this);
        return $this;
    }

    public function removeProduct(Product $product)
    {
        $this->products->removeElement($product);
    }

    public function getProducts()
    {
        return $this->products;
    }
    
    /** 
    * get pricing as string
    * return string
    */
    public function getPricingAsString()
    {
        $i = $this->getPricingType();    
        if ($i > -1) {  
            return AllTypeController::getCustomerPricing()[$i];
        } else {
            return null;
        }
        
    }
     /** 
    * get pricing as string
    * return string
    */
    public function getImportAsString()
    {
        $i = $this->getImportType();    
        if ($i > -1) {  
            return AllTypeController::getCustomerImport()[$i];
        } else {
            return null;
        }
        
    }
    
    
    public function validate(ExecutionContextInterface $context)
    {
        if ($this->getPromoCodes() == null && ($this->isAutoAcquisition() || $this->isGlobalPromo())) {
            $context->addViolationAt(
                'importType','Dpp.error.customer.not_promoCode',array(), null);
        }
        if (!stripos($this->getDefaultMsg(), '[$code$]')) {
            $context->addViolationAt(
                'defaultMsg','Dpp.error.customer.noValideMsg',array(), null);
        } 
    }
    
    static function getWithDefault() {
        $msg = "C'est votre [$". "visite$] visite.  Vous bénéficiez du code promotion [$" . "code$].";
        $customer = new Customer();
        $customer->setVisitTimeInterval(24);
        $customer->setImportType(0);
        $customer->setDefaultMsg($msg);
        $customer->setAutoAcquisition(False);
        $customer->setGlobalPromo(False);
        $customer->setCategoryPromoo(False);
        return $customer;
    }
    
    
}

src/Dpp/CustomersBundle/Controller/CategoryController.php
<?php

// src\Dpp\CustomersBundle\Controller\CategoryController.php

namespace Dpp\CustomersBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use JMS\SecurityExtraBundle\Annotation\Secure;
use Dpp\CustomersBundle\Entity\Customer;
use Dpp\CustomersBundle\Entity\Category;
use Dpp\CustomersBundle\Form\Category\CategoryType;



class CategoryController extends Controller
{    

    public function listByUserCustomerAction() {
        if ($this->get('security.context')->isGranted('ROLE_ADMIN')) {
            return $this->redirect( $this->generateUrl('dpp_customers_list') );
        }
        $user = $this->container->get('security.context')->getToken()->getUser();
        $customer = $user->getCustomer();
        if (!$customer == null) {
            return $this->listByCustomer($customer);
        }
        throw new AccessDeniedException("Vous n'étez pas autorisé.");       
    }


    public function listByCustomerAction($customerRef)
    {   
        $entityManager = $this->getDoctrine()->getManager();
        $customer = $entityManager->getRepository('DppCustomersBundle:Customer')->findOneBy(array('domaine' => $customerRef));
        if (!$customer == null) {
            $categorys = $entityManager->getRepository('DppCustomersBundle:Category')->getAllHierarchyCustomer($customer);
            $returnUrl = $this->generateUrl('dpp_customers_update', array('customerRef' => $customer->getDomaine() ));
            return $this->render('DppCustomersBundle:Categorys:categorysCustomerList.html.twig',array('categorys' => $categorys, 
                                                                                                    'customer'=> $customer,
                                                                                                    'returnUrl'=>$returnUrl));
        }
        return $this->redirect( $this->generateUrl('dpp_customers_list') );
    
    }
    
    private function listByCustomer(Customer $customer)
    {   
        $entityManager = $this->getDoctrine()->getManager();
        if (!$customer == null) {
            $returnUrl = $this->generateUrl('dpp_customers_update', array('customerRef' => $customer->getDomaine() ));
            $categorys = $entityManager->getRepository('DppCustomersBundle:Category')->findby(array('customer' => $customer));
            return $this->render('DppCustomersBundle:Categorys:categorysCustomerList.html.twig',array('categorys' => $categorys,
                                                                                                    'customer'=> $customer,
                                                                                                    'returnUrl'=>$returnUrl));
        }
        return $this->redirect( $this->generateUrl('dpp_customers_list') );
    
    }
    
    
    
    public function createAction($customerRef)
    {
		$entityManager = $this->getDoctrine()->getManager();
        $customer = $entityManager->getRepository('DppCustomersBundle:Customer')->findOneBy(array('domaine' => $customerRef));
        if ($customer == null) {
            return listAllAction();
        }
        $category = new Category(); // Création de l'entité
        $category->setCustomer($customer);
        $form = $this->createForm(new CategoryType($category->getId(), $customer), $category);        
        $request = $this->get('request');
        if ($request->getMethod() == 'POST') { // aprés la validation user
            $form->bind($request); // on remplis le $form
            if ($form->isValid()) {                       
                $entityManager->persist($category);
                $entityManager->flush();
                $this->get('session')->getFlashBag()->add('info', 'Category enregistré');
                return $this->redirect( $this->generateUrl('dpp_category_add', array('customerRef'=>$customerRef)));
            } 
        }
        $returnUrl = $this->generateUrl('dpp_categorys_customer', array('customerRef' => $customer->getDomaine() ));
        return $this->render('DppCustomersBundle:Categorys:categoryCreate.html.twig', array('form' => $form->createView(),
                                                                                        'returnUrl' => $returnUrl,
                                                                                        'tabPromoCodes' => null));
    }
    
    public function updateAction($id)
    {
		$entityManager = $this->getDoctrine()->getManager();
        $category = $entityManager->getRepository('DppCustomersBundle:Category')->findOneBy(array('id' => $id));
        if ($category == null) {
            return listAllAction();
        }
        $tabPromoCodes = json_decode($category->getPromoCodes());
        if (!$tabPromoCodes == null) {
            $category->setPromoCodes( substr($category->getPromoCodes(),1,strlen($category->getPromoCodes())-2));
        }
        $form = $this->createForm(new CategoryType($category->getId(), $category->getCustomer()), $category);        
        $request = $this->get('request');
        if ($request->getMethod() == 'POST') { // aprés la validation user
            $form->bind($request); // on remplis le $form
            if ($form->isValid()) {   
                if (!$category->getPromoCodes() == null) {
                    $tabPromoCodes = json_decode($category->getPromoCodes());
                    usort($tabPromoCodes, array($this, 'UcompCode'));
                    $category->setPromoCodes(json_encode($tabPromoCodes));
                }                  
                $entityManager->persist($category);
                $entityManager->flush();
                return $this->listByCustomer($category->getCustomer());
            } 
        }
        $returnUrl = $this->generateUrl('dpp_categorys_customer', array('customerRef' => $category->getCustomer()->getDomaine() ));
        return $this->render('DppCustomersBundle:Categorys:categoryUpdate.html.twig', array('form' => $form->createView(),
                                                                                        'returnUrl' => $returnUrl,
                                                                                        'tabPromoCodes' => $tabPromoCodes));
    }
    
    public function deleteAction($id)
    {
		$entityManager = $this->getDoctrine()->getManager();
        $category = $entityManager->getRepository('DppCustomersBundle:Category')->findOneBy(array('id' => $id));
        if ($category == null) {
            return $this->redirect( $this->generateUrl('dpp_customers_list') );
        }
        $customer = $category->getCustomer();       
        $entityManager->remove($category);
        $entityManager->flush();
        return $this->listByCustomer($customer);
    }
    /* 
    * sort promo table 
    */
    private function UcompCode(Array $l1, Array $l2) {
        if ($l1[0] < $l2[0]) {
            return -1;
        } elseif ($l1[0] == $l2[0]) {
            return 0;
        } else {
            return 1;
        }
    }
    
}

src/Dpp/CustomersBundle/Resources/views/Categorys/SAVE categorysCustomerList.html.twig
{# src/Dpp/CustomersBundle/Resources/views/Categorys/categorysCustomerList.html.twig #}
 
{% extends "DppCustomersBundle::layout.html.twig" %}

{% block title %}
    Liste  - {{ parent() }}
{% endblock %}
{% block Dpp_body %}
<div class="row">
    <h3 class="txtcentre">{{ 'Dpp.category.liste'|trans }} : <b class="txttiger">{{customer.name }}</b></h3>
    {% for flashMessage in app.session.flashbag.get('info') %}
        <div class="txtjaune">{{ flashMessage }}</div>
    {% endfor %}
</div>
<div class="row">
    
    
    {% if categorys %}
        <div class="table-responsive ">
            <table class=" table-striped table-bordered " >
                <thead>
                    <tr>
                        <th class="col-lg-2">{{ 'Dpp.global.name'|trans }}</th>
                        <th class="col-lg-2">{{ 'Dpp.category.parent'|trans }}</th>
                        <th class="col-lg-2">{{ 'Dpp.global.urlRef'|trans }}</th>
                        <th class="col-lg-2"></th>
    
                    </tr>
                </thead>  
                <tbody>
                {% for category in categorys %}
                <tr>
                    <td>{{ category.name }}</td>
                    {% if category.parent %}
                        <td>{{ category.parentName }}</td>
                    {% else %}
                        <td></td>
                    {% endif %}
                    <td>{{ category.urlRef }}</td>
                    <td>
                        <a href="{{ path('dpp_category_edit', {'id': category.id }) }}" class="grph-btn" style= "float: left;" >
                            <img src="/dynaprice/web/img/icones/write_obj.gif">&nbsp;{{ "Dpp.global.edit"|trans }}</a>
                        &nbsp;&nbsp;
                        <a href="{{ path('dpp_category_delete', {'id': category.id }) }}" class="btn-default" onclick='return(confirm("{{ 'Dpp.global.confirm_delete'|trans}}" ))' >
                            <img src="/dynaprice/web/img/icones/delete_obj.gif">&nbsp;{{ "Dpp.global.delete"|trans }}</a>
                        
                    </td>                 
                </tr>
                {% endfor %}
                </tbody>
            </table><br>
        </div>
    {% else %}
        {{ 'Dpp.category.notfound'|trans }}
    {% endif %}
    </div>
</div>
<div class="row">
        
        <div class="col-lg-3">
            <a href=" {{ returnUrl }} " class="grph-btn "><i class="icon-chevron-left"></i>{{ 'Dpp.category.customer_return'|trans }}</a>
        </div>
        <div class="col-lg-3 col-lg-offset-4">
            <a href="{{ path('dpp_category_add', {'customerRef': customer.domaine }) }}" class="grph-btn">
                <img src="/dynaprice/web/img/icones/add_obj.gif">&nbsp{{ 'Dpp.category.add_buton'|trans }}
            </a>
        </div>
</div> 

{% endblock %}
  

src/Dpp/CustomersBundle/Resources/views/Categorys/categoryCreate.html.twig
{# src\Dpp\CustomersBundle\Resources\views\Categorys\categoryCreate.html.twig #}

{% extends "DppCustomersBundle::layout.html.twig" %}

{% block Dpp_body %}

<h3> {{ 'Dpp.category.add'|trans }} </h3>
<div class="label-and-input">
	{% include "DppCustomersBundle:Categorys:categoryForm.html.twig" %}
</div>
	
{% endblock %}

src/Dpp/CustomersBundle/Resources/views/Categorys/categoryForm.html.twig
{# src/Dpp/CustomersBundle/Resources/views/Categorys/categoryForm.html.twig #}
 {% form_theme form 'DppCustomersBundle:Default:fields.html.twig' %}
 
<script type="text/javascript" src="{{ asset('js/dppTabPromo.js') }}"></script>

{% for flashMessage in app.session.flashbag.get('info') %}
    <div class="txtjaune">{{ flashMessage }}</div>
{% endfor %} 
<div class="txtred">{{ form_errors(form.urlRef) }} {{ form_errors(form.parent) }}</div>

<div class="row">
    <form method="post"  Onsubmit="return DppComputeTabCode($('#dpp_customersbundle_category_categorytype_promoCodes'))"   {{ form_enctype(form) }}>
        <div class="txtred">{{ form_errors(form) }}</div>
        <div class="zone-bordered ">
            <div class="row">
                <div class="col-lg-2 col-lg-offset-1">{{ form_label(form.customerName) }}</div><div class="col-lg-3">{{ form_widget(form.customerName) }}</div>
                <div class="col-lg-2 "></div><div class="col-lg-2"></div>
            </div>
            <div class="row">
                <div class="col-lg-2 col-lg-offset-1">{{ form_label(form.name) }}</div><div class="col-lg-3">{{ form_widget(form.name) }}</div>
                <div class="col-lg-2 ">{{ form_label(form.urlRef) }}</div><div class="col-lg-2">{{ form_widget(form.urlRef) }}  </div>
            </div>
            <div class="row">
                <div class="col-lg-2 col-lg-offset-1">{{ form_label(form.parent) }}</div><div class="col-lg-3">{{ form_widget(form.parent) }}</div>
                <div class="col-lg-2 "></div><div class="col-lg-2"></div>
            </div>
            <div class="row">
                <div class="col-lg-2 col-lg-offset-1">{{ form_label(form.pricingType) }}</div><div class="col-lg-3">{{ form_widget(form.pricingType) }}</div>
                <div class="col-lg-2">{{ form_label(form.state) }}</div><div class="col-lg-2">{{ form_widget(form.state) }}</div>
            </div>
            {{ form_rest(form) }}
        </div>
        <div class="row">
            <h4 class="txtcentre">{{ "Dpp.global.promoCodes"|trans }}</h4>
        </div>    
        <div class="row">
            <div class="col-lg-2 col-lg-offset-2">Nb des visites</div>
            <div class="col-lg-2 col-lg-offset-1">Code promo</div>
            <div class="col-lg-2 col-lg-offset-1">Message</div>
        </div>
        <div class="row">
            <div class="col-lg-1 col-lg-offset-2"><input type="number" name="visites" id="visites" /></div>
            <div class="col-lg-1 col-lg-offset-2"><input type="text" name="code" id="code" /></div>
            <div class="col-lg-2 col-lg-offset-2"><input type="text"  size="64" name="message" id="message" /></div>
            <div class="col-lg-2 "><a href="#" class="grph-btn" onclick="DppAddRow($('#dpp_customersbundle_category_categorytype_promoCodes'));">
                        <img src="/dynaprice/web/img/icones/add_obj.gif">&nbsp{{ "Dpp.global.add_code"|trans }}</a>                
            </div>
        </div><br>
        <div class="row">
            <div class="col-lg-1 " ></div>   
            <div class="table-responsive ">
                <table id="tableau" class="table-striped table-bordered">
                    <thead>
                        <tr>
                            <th class="col-lg-1">Nb Visites</th>
                            <th class="col-lg-1">Code</th>
                            <th class="col-lg-2">Texte</th>
                            <th class="col-lg-1"></th>
                        </tr>
                    </thead>
                    <tbody>
                    {% if tabPromoCodes %}
                        {% for ligCode in tabPromoCodes %}
                        <tr>
                            <td>{{ ligCode[0] }}</td>
                            <td>{{ ligCode[1] }}</td>
                            <td>{{ ligCode[2] }}</td>
                            <td><a href"#"  onclick="DppDeleteRow(this);" class="btn-default"><img src="/dynaprice/web/img/icones/delete_obj.gif">&nbsp{{ "Dpp.global.delete"|trans }}</a></td>
                        </tr>
                        {% endfor %}
                    {% endif %}
                    </tbody>
                </table><br><br>
            </div>
           <div class="col-lg-1 " ></div>  
        </div>
        <div class="row">
            <div class="col-lg-2"> 
                <a href=" {{ returnUrl }} " class="grph-btn "><i class="icon-chevron-left"></i>Cancel</a>        
            </div>
            <div class="col-lg-2 col-lg-offset-2"> 
                <input type="submit" class="btn pull-right btn-primary"  />      
            </div>
        </div>
    </form>
</div>

src/Dpp/CustomersBundle/Resources/views/Categorys/categoryUpdate.html.twig
{# src\Dpp\CustomersBundle\Resources\views\Categorys\categoryUpdate.html.twig #}

{% extends "DppCustomersBundle::layout.html.twig" %}

{% block Dpp_body %}

<h3> {{ 'Dpp.category.update'|trans }} </h3>
<div class="label-and-input">
	{% include "DppCustomersBundle:Categorys:categoryForm.html.twig" %}
</div>
	
{% endblock %}

src/Dpp/CustomersBundle/Resources/views/Categorys/categorysCustomerList.html.twig
{# src/Dpp/CustomersBundle/Resources/views/Categorys/categorysCustomerList.html.twig #}
 
{% extends "DppCustomersBundle::layout.html.twig" %}

{% block title %}
    Liste  - {{ parent() }}
{% endblock %}
{% block Dpp_body %}
<div class="row">
    <h3 class="txtcentre">{{ 'Dpp.category.liste'|trans }} : <b class="txttiger">{{customer.name }}</b></h3>
    {% for flashMessage in app.session.flashbag.get('info') %}
        <div class="txtjaune">{{ flashMessage }}</div>
    {% endfor %}
</div>
<div class="row">
    <div class="col-lg-1"></div>
    
    {% if categorys %}
        <div class="table-responsive ">
            <table class=" table-striped table-bordered " >
                <thead>
                    <tr>
                        <th  style="width: 3%;"></th>
                        <th class="col-lg-2">{{ 'Dpp.global.name'|trans }}</th>
                        <th class="col-lg-2">{{ 'Dpp.category.parent'|trans }}</th>
                        <th class="col-lg-2">{{ 'Dpp.global.urlRef'|trans }}</th>
                        <th class="col-lg-2"></th>  
                    </tr>
                </thead>  
                <tbody>
                {% for category in categorys %}
                <tr>
                    {% if category.promoCodes %}
                        <td data-toggle="collapse" data-target='#{{ category.id }}' class="clickable"><img src="/dynaprice/web/img/icones/add_obj.gif" alt='codes promo' ></td>
                    {% else %}
                    <td></td>
                    {% endif %}
                    <td>{{ category.name }}</td>
                    {% if category.parent %}
                        <td>{{ category.parentName }}</td>
                    {% else %}
                        <td></td>
                    {% endif %}
                    <td>{{ category.urlRef }}</td>
                    <td>
                        <div class="btn-group pull-right">
                            <button type="button" class="btn grph-btn ">Actions</button>
                            <button type="button" class="grph-btn pull-right dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                                <span class="sr-only">Toggle Dropdown</span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ path('dpp_category_edit', {'id': category.id }) }}">
                                <img src="/dynaprice/web/img/icones/write_obj.gif">&nbsp;{{ "Dpp.global.edit"|trans }}</a></li>
                                <li><a href="{{ path('dpp_category_delete', {'id': category.id }) }}" onclick='return(confirm("{{ 'Dpp.global.confirm_delete'|trans}}" ))' >
                                <img src="/dynaprice/web/img/icones/delete_obj.gif">&nbsp;{{ "Dpp.global.delete"|trans }}</a></li>
                            </ul>
                        </div> 
                    </td>                 
                </tr>
                <tr id="{{ category.id }}" class="collapse">
                    <td colspan="5">
                    {% if category.promoCodes %}             
                        <div class=" col-lg-6 col-lg-offset-1" >
                            <table class=" table-interne " >
                                <thead>
                                    <tr>
                                        <th class="col-lg-2">Nb Visites</th>
                                        <th class="col-lg-2">Code promo</th>
                                        <th class="col-lg-2">Texte</th>
                                    </tr>
                                </thead>
                                <tbody>                               
                                    {% for ligCode in category.promoCodesAsArray %}
                                    <tr>
                                        <td>{{ ligCode[0] }}</td>
                                        <td>{{ ligCode[1] }}</td>
                                        <td>{{ ligCode[2] }}</td>
                                    </tr>
                                    {% endfor %}                      
                                </tbody>
                            </table>
                        </div>
                    {% endif %}
                    </td>
                </tr>
                {% endfor %}
                
                </tbody><tr></tr>
            </table><br><br><br>
        </div>
    {% else %}
        {{ 'Dpp.category.notfound'|trans }}
    {% endif %}
    </div>
</div>
<div class="row">
        
        <div class="col-lg-3">
            <a href=" {{ returnUrl }} " class="grph-btn "><i class="icon-chevron-left"></i>{{ 'Dpp.category.customer_return'|trans }}</a>
        </div>
        <div class="col-lg-3 col-lg-offset-4">
            <a href="{{ path('dpp_category_add', {'customerRef': customer.domaine }) }}" class="grph-btn">
                <img src="/dynaprice/web/img/icones/add_obj.gif">&nbsp{{ 'Dpp.category.add_buton'|trans }}
            </a>
        </div>
</div> 

{% endblock %}
  